# Generated by Django 3.2.4 on 2024-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_validated',
            field=models.BooleanField(default=False),
        ),
    ]
