# Generated by Django 3.2.4 on 2024-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_otp_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='defaultProfilePic.webp', upload_to='profile_images'),
        ),
    ]
