# Generated by Django 3.2.4 on 2024-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240321_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='defaultProfileImg.jpeg', upload_to='profile_images'),
        ),
    ]
