# Generated by Django 3.2.4 on 2024-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
