# Generated by Django 3.2.4 on 2024-04-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20240419_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='group_images'),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='participants',
            field=models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='travel_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
