# Generated by Django 5.0.4 on 2024-05-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preference_given', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('preferences', models.ManyToManyField(to='core.preferenceoption')),
            ],
        ),
    ]
