# Generated by Django 5.0.4 on 2024-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_preferenceoption_post_category_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_preference_given',
            field=models.BooleanField(default=False),
        ),
    ]
