# Generated by Django 5.0.4 on 2024-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_post_is_preference_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_preference_given',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_preference_given',
            field=models.BooleanField(default=False),
        ),
    ]
