# Generated by Django 5.0.4 on 2024-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_post_is_preference_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenceoption',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
