# Generated by Django 5.0.4 on 2024-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_preferenceoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgroup',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
