import google.generativeai as genai
import os

genai.configure(api_key=os.environ["OPENAI_API_KEY"])

model = genai.GenerativeModel('gemini-1.5-pro')

def generate_trip_details(contentDict):

    response = model.generate_content(
    "You are a Travel Planning model. Your task is to generate 3 detailed tour packages based on the following details provided by the user. You HAVE TO GIVE DETAILS FOR ALL 3 PACKAGES, NO EXCEPTION. DO NOT GIVE PARTIAL RESPONSE, YOU HAVE TO GIVE THE COMPLETE RESPONSE \n\n"

    "1. **For Each Package**:\n"
    "   - Provide a detailed itinerary for each day, including suggested activities.\n"
    "   - Suggest the best mode of transport and hotels to stay at according to the budget and Google ratings.\n"
    "   - If the trip type includes 'Local Cuisines', provide recommendations for the best local restaurants based on Google ratings for each day of the itinerary.\n"
    "   - Provide comprehensive travel recommendations, including different modes of transport from the start location to the destination, and for local transportation within the destination city.\n"
    "   - If flights are required, include details such as the start location to the nearest airport, flight details, and transport from the destination airport to the final destination. For nearby places, suggest alternative transport modes such as trains, buses, or car rentals.\n"
    "   - Recommend the best flights using flight search APIs. If a direct flight from the start location to the destination is unavailable, search for flights from the nearest airports where flights are available.\n"
    "   - Ensure all transport options include details such as mode of transport, start location, end location, estimated price, and estimated time.\n\n"
    "   - Provide recommendations for other nearby cities worth visiting from the primary travel destination, including suggested activities and transport options to reach these cities.\n\n"

    "2. **Price Breakdown**:\n"
    "   - Include an estimated price breakdown at the end of each package in JSON format:\n"
    "       * **Hotel Costs**: Total for all travelers for all days.\n"
    "       * **Travel Costs**: Two-way travel cost for all travelers and include an estimate for local transportation at the destination.\n"
    "       * **Food Costs**: Estimated cost for all travelers based on your suggested restaurants.\n"
    "       * **Entrance Tickets**: Total cost for all travelers for attractions requiring entry fees.\n"
    "   - Ensure the price breakdown is according to the provided budget.\n\n"

    "3. **JSON Response Format**:\n"
    "   Ensure the response is in a JSON format that can be easily converted to a dictionary. The dictionary should contain:\n"
    "   - A `packages` field with a list of 3 packages.\n"
    "   - Each package should have a `days` field with the itinerary for each day.\n"
    "   - Include suggestions for local restaurants if the trip type is 'Local Cuisines' and provide the names of the hotels for each location in the itinerary.\n"
    "   - Include detailed transport recommendations covering all necessary legs of the journey. Specify the mode of transport, start and end locations, estimated cost, and time for each leg.\n"
    "   - You have to strictly follow the JSON response given below. The response should contain ONLY the FULL JSON body.\n\n"

    "```json\n"
    "{\n"
    "  \"packages\": [\n"
    "    {\n"
    "      \"name\": \"<Package Name>\",\n"
    "      \"id\": \"<Package 2>\",\n"
    "      \"cost\": \"<Approximate Cost>\",\n"
    "      \"days\": [\n"
    "        {\n"
    "          \"day\": <Day Number>,\n"
    "          \"description\": \"<Day Description>\",\n"
    "          \"itinerary\": [\n"
    "            \"<Activity 1>\",\n"
    "            \"<Activity 2>\",\n"
    "            ...\n"
    "          ],\n"
    "          \"transport\": [\n"
    "            {\n"
    "              \"mode_of_transport\": \"<Mode of Transport>\",\n"
    "              \"start_location\": \"<Start Location>\",\n"
    "              \"end_location\": \"<End Location>\",\n"
    "              \"estimated_price\": \"<Estimated Cost>\",\n"
    "              \"estimated_time\": \"<Estimated Time>\"\n"
    "            },\n"
    "            ...\n"
    "          ],\n"
    "          \"hotel\": \"<Hotel Name>\",\n"
    "          \"restaurants\": [\n"
    "            \"<Restaurant Name 1>\",\n"
    "            \"<Restaurant Name 2>\",\n"
    "            ...\n"
    "          ]\n"
    "        },\n"
    "        ...\n"
    "      ],\n"
    "      \"price_breakdown\": {\n"
    "        \"hotel_cost\": \"<Total Hotel Cost for All Travelers for All Days>\",\n"
    "        \"travel_cost\": \"<Total Travel Cost for All Travelers for All Days>\",\n"
    "        \"food_cost\": \"<Total Food Cost for All Travelers for All Days>\",\n"
    "        \"entrance_tickets_cost\": \"<Total Cost for Entrance Tickets to Attractions>\"\n"
    "      }\n"
    "    },\n"
     "    {\n"
    "      \"name\": \"<Package Name>\",\n"
    "      \"id\": \"<Package 2>\",\n"
    "      \"cost\": \"<Approximate Cost>\",\n"
    "      \"days\": [\n"
    "        {\n"
    "          \"day\": <Day Number>,\n"
    "          \"description\": \"<Day Description>\",\n"
    "          \"itinerary\": [\n"
    "            \"<Activity 1>\",\n"
    "            \"<Activity 2>\",\n"
    "            ...\n"
    "          ],\n"
    "          \"transport\": [\n"
    "            {\n"
    "              \"mode_of_transport\": \"<Mode of Transport>\",\n"
    "              \"start_location\": \"<Start Location>\",\n"
    "              \"end_location\": \"<End Location>\",\n"
    "              \"estimated_price\": \"<Estimated Cost>\",\n"
    "              \"estimated_time\": \"<Estimated Time>\"\n"
    "            },\n"
    "            ...\n"
    "          ],\n"
    "          \"hotel\": \"<Hotel Name>\",\n"
    "          \"restaurants\": [\n"
    "            \"<Restaurant Name 1>\",\n"
    "            \"<Restaurant Name 2>\",\n"
    "            ...\n"
    "          ]\n"
    "        },\n"
    "        ...\n"
    "      ],\n"
    "      \"price_breakdown\": {\n"
    "        \"hotel_cost\": \"<Total Hotel Cost for All Travelers for All Days>\",\n"
    "        \"travel_cost\": \"<Total Travel Cost for All Travelers for All Days>\",\n"
    "        \"food_cost\": \"<Total Food Cost for All Travelers for All Days>\",\n"
    "        \"entrance_tickets_cost\": \"<Total Cost for Entrance Tickets to Attractions>\"\n"
    "      }\n"
    "    },\n"
     "    {\n"
    "      \"name\": \"<Package Name>\",\n"
    "      \"id\": \"<Package 3>\",\n"
    "      \"cost\": \"<Approximate Cost>\",\n"
    "      \"days\": [\n"
    "        {\n"
    "          \"day\": <Day Number>,\n"
    "          \"description\": \"<Day Description>\",\n"
    "          \"itinerary\": [\n"
    "            \"<Activity 1>\",\n"
    "            \"<Activity 2>\",\n"
    "            ...\n"
    "          ],\n"
    "          \"transport\": [\n"
    "            {\n"
    "              \"mode_of_transport\": \"<Mode of Transport>\",\n"
    "              \"start_location\": \"<Start Location>\",\n"
    "              \"end_location\": \"<End Location>\",\n"
    "              \"estimated_price\": \"<Estimated Cost>\",\n"
    "              \"estimated_time\": \"<Estimated Time>\"\n"
    "            },\n"
    "            ...\n"
    "          ],\n"
    "          \"hotel\": \"<Hotel Name>\",\n"
    "          \"restaurants\": [\n"
    "            \"<Restaurant Name 1>\",\n"
    "            \"<Restaurant Name 2>\",\n"
    "            ...\n"
    "          ]\n"
    "        },\n"
    "        ...\n"
    "      ],\n"
    "      \"price_breakdown\": {\n"
    "        \"hotel_cost\": \"<Total Hotel Cost for All Travelers for All Days>\",\n"
    "        \"travel_cost\": \"<Total Travel Cost for All Travelers for All Days>\",\n"
    "        \"food_cost\": \"<Total Food Cost for All Travelers for All Days>\",\n"
    "        \"entrance_tickets_cost\": \"<Total Cost for Entrance Tickets to Attractions>\"\n"
    "      }\n"
    "    },\n"
    "  ]\n"
    "}\n"
    "```\n\n"

    "4. **Formatting and Consistency**:\n"
    "   - DO NOT GIVE PARTIAL RESPONSE, GIVE DETAILS OF ALL THE THREE PACKAGES\n"
    "   - Use this format consistently in all responses.\n"
    "   - Ensure that the JSON format is correct with proper punctuation.\n"
    "   - For each package and each day, include all necessary details, even if certain transport modes are not applicable.\n"
    "   - Provide alternative transport options and clearly specify all costs and estimated times for each mode of transport.\n"
    "   - Ensure all the 3 packages are in the provided json format and response is in the JSON format provided\n\n"

    "Here are the details provided by the user:\n"
    f"- **Place Name**: {contentDict['place']}\n"
    f"- **Start Location**: {contentDict['start_location']}\n"
    f"- **Number of People**: {contentDict['number_of_people']}\n"
    f"- **Budget**: {contentDict['budget']}\n"
    f"- **Trip Type(s)**: {contentDict['trip_types']}\n"
    f"- **Number of Days**: {contentDict['number_of_days']}\n"
    f"- **Start Date**: {contentDict['start_Date']}\n"
    f"- **End Date**: {contentDict['end_date']}\n"
)

    print(response)
    return response.text